### ISSUE TITLE
Add wheel file (.whl) on PyPI

### ISSUE THREAD

**Issue by svisser** [ambitioninc/fleming#26]
The Python wheel format has various improvements (when deploying) over a source release, see http://pythonwheels.com. In recent pip releases these files are selected rather than source releases.

**Comment by wesleykendall** [comment]
The wheel distribution has now been uploaded in version 0.4.3 and will continue to be used as the format of choice afterwards (we just actually recently switched to only using wheels at our org). Thanks!

**Comment by svisser** [comment]
Ah, very quick - thanks! It appears `fleming` in combination with `pytz` and `dateutil` are all the datetime dependencies I now need.
